autoDiscovery:
    clusterName: {{cluster_name}}
awsRegion: {{region_name}}
image:
    tag: v1.27.3
nodeSelector:
  eks.amazonaws.com/capacityType: ON_DEMAND
podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
extraArgs:
    skip-nodes-with-system-pods: false
    scale-down-unneeded-time: 2m
    scale-down-unready-time: 5m
rbac:
    serviceAccount:
        create: false
        name: cluster-autoscaler

  